package za.co.quantive.app.data.remote.api

import kotlinx.serialization.Serializable
import za.co.quantive.app.domain.entities.*

/**
 * Backend API for business analytics and dashboard data
 * All metrics, calculations, and insights are generated by the backend
 */
interface AnalyticsApi {
    
    /**
     * Get dashboard overview - all metrics calculated by backend
     */
    suspend fun getDashboardOverview(
        dateRange: DateRange? = null
    ): ApiResponse<DashboardOverview>
    
    /**
     * Get detailed business metrics
     */
    suspend fun getBusinessMetrics(
        dateRange: DateRange? = null,
        granularity: MetricGranularity = MetricGranularity.MONTHLY
    ): ApiResponse<BusinessMetrics>
    
    /**
     * Get revenue analytics
     */
    suspend fun getRevenueAnalytics(
        dateRange: DateRange? = null
    ): ApiResponse<RevenueAnalytics>
    
    /**
     * Get customer analytics
     */
    suspend fun getCustomerAnalytics(
        dateRange: DateRange? = null
    ): ApiResponse<CustomerAnalytics>
    
    /**
     * Get payment analytics
     */
    suspend fun getPaymentAnalytics(
        dateRange: DateRange? = null
    ): ApiResponse<PaymentAnalytics>
    
    /**
     * Get tax/compliance analytics
     */
    suspend fun getTaxAnalytics(
        dateRange: DateRange? = null
    ): ApiResponse<TaxAnalytics>
    
    /**
     * Export business report - backend generates comprehensive report
     */
    suspend fun exportBusinessReport(
        reportType: ReportType,
        dateRange: DateRange,
        format: ExportFormat = ExportFormat.PDF
    ): ApiResponse<ExportResponse>
}

// All analytics models are defined in AnalyticsModels.kt